baseURL = 'https://blog.sedawk.ninja'
languageCode = 'en-us'
title = 'Sed? Awk? Ninja!'
year = '2025'

[params]
name = "Nate Thompson"
tagline = "Linux • Cloud • Security • Architecture"
subtitle = "Techie, tinkerer, and Systems Architect who lives in the terminal."
heroImage = "/images/hero-norway.jpg"
