baseURL = 'https://blog.sedawk.ninja'
languageCode = 'en-us'
title = 'Sed? Awk? Ninja!'
year = '2025'
theme = ''

[params]
name = "Nathaniel Thompson"
tagline = "Linux • Cloud • Security • Architecture"
subtitle = "Techie, tinkerer, and systems architect who lives in the terminal."
heroImage = "https://unsplash.com/photos/a-foggy-forest-with-trees-Sqgkj4CnXxE"
